### ISSUE TITLE
Global detection hurts isomorphic rendering

### ISSUE THREAD

**Issue by rauchg** [NervJS/nerv#12]
`require('nervjs')` throws in Node.js:

```
Error: unable to locate global object
    at /Users/rauchg/Projects/next-news/node_modules/nervjs/dist/index.js:17:11
    at Object.<anonymous> (/Users/rauchg/Projects/next-news/node_modules/nervjs/dist/index.js:18:2)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
```

I had to work around it by manually setting `self = this`.

**Comment by luckyadam** [comment]
Hello, You should use `nerv-server` for isomorphic rendering

**Comment by yuche** [comment]
Hi, Guillermo. Very nice to have you here. 

Thanks for point this out. You can try `npm i nervjs@beta` and test.

PS:
Big fan of ZEIT.

**Comment by DuncanMacWeb** [comment]
Hi @yuche — great project, thank you 👍 

Have published this change to npm yet? I’m still getting

```
  /project/build/server/webpack:/node_modules/nervjs/dist/index.esm.js:25
  var doc = isBrowser ? document : fakeDoc;
  ^
  ReferenceError: document is not defined
      at Object.<anonymous> (/project/build/server/webpack:/node_modules/nervjs/dist/index.esm.js:25:1)
```

even though I have installed nerv beta; `package.json`:

```
    "dependencies": {
        "nerv-redux": "^1.2.5-beta.1",
        "nerv-server": "^1.2.5-beta.1",
        "nervjs": "^1.2.5-beta.1",
    }
```

Any help much appreciated.

**Comment by luckyadam** [comment]
@DuncanMacWeb Hello!Are you running in browser then got the error?

**Comment by yuche** [comment]
@DuncanMacWeb According to #24 , the problem have been solved. Would you reproduce a basic example? Thank you.
