### ISSUE TITLE
NervJS 1.4 beta3 test-utils 报错

### ISSUE THREAD

**Issue by ZhangJian-3ti** [NervJS/nerv#121]
Works well in 1.3.x版本。But broke in 1.4.

TypeError: Cannot read property 'forEach' of undefined

      34 | 
      35 |   it(`somehow throw error`, () => {
    > 36 |     const component = renderIntoDocument(<Campaign campaignProps={mockCampaign.events} />)
         |                       ^
      37 |     const componentDom = findDOMNode(component, 'swiperContent')
      38 |     const items = componentDom.querySelectorAll('.swiperImage')
 
      at forEach (node_modules/nervjs/src/hooks.ts:123:11)
      at renderComponent (node_modules/nervjs/dist/index.js:1702:5)
      at renderComponent (node_modules/nervjs/src/lifecycle.ts:98:20)
      at ComponentWrapper.mountComponent [as init] (node_modules/nervjs/src/full-component.ts:47:17)
      at init (node_modules/nervjs/src/vdom/create-element.ts:27:47)
      at createElement (node_modules/nervjs/src/lifecycle.ts:69:10)
      at mountVNode (node_modules/nervjs/src/lifecycle.ts:107:28)
      at ComponentWrapper.mountComponent [as init] (node_modules/nervjs/src/full-component.ts:47:17)
      at createElement (node_modules/nerv-test-utils/node_modules/nervjs/dist/index.js:1333:29)
      at mountVNode (node_modules/nerv-test-utils/node_modules/nervjs/dist/index.js:1454:12)
      at Object.render (node_modules/nerv-test-utils/node_modules/nervjs/dist/index.js:1729:15)
      at renderIntoDocument (node_modules/nerv-test-utils/src/index.ts:16:16)

**Comment by yuche** [comment]
出现这个错误最大的可能是在这个测试页面 JSX 不是由 1.4 beta 版本的 nerv 创建的，1.4 版本 `components.effect` 一定是一个数组。
你可以检查一下 nerv-test-utils 以及它依赖的 nervjs 是不是 1.4 版本。

**Comment by ZhangJian-3ti** [comment]
Just tried update the dependencies manually, the problem still exists.

**Comment by yuche** [comment]
我试了可以。如果你觉得不行可以去 https://codesandbox.io/s/r4qzmo75np 复现

**Comment by ZhangJian-3ti** [comment]
added test-utils can reproduce this:
https://codesandbox.io/s/wnm08wm825

**Comment by yuche** [comment]
https://codesandbox.io/s/o6y5kz8xq
那是因为  @tarojs/components 的 nervjs 依赖也没有更新到 beta

**Comment by ZhangJian-3ti** [comment]
After upgrade the dependencies manually, it works well as expected. Thanks.
Hope new version released soon.

**Comment by cjmafei** [comment]
![image](https://user-images.githubusercontent.com/23433659/113669466-653be280-96e6-11eb-961c-3d42fa719c58.png)

![image](https://user-images.githubusercontent.com/23433659/113669497-7389fe80-96e6-11eb-9554-592690ef0cab.png)

![image](https://user-images.githubusercontent.com/23433659/113669517-7a187600-96e6-11eb-9ec4-4436b1643b43.png)
  @yuche 我这边出现了同样的问题，是我哪个依赖的版本不对吗？
