### ISSUE TITLE
TypeError: external_nervjs_default.a.memo is not a function

### ISSUE THREAD

**Issue by mydearxym** [NervJS/nerv#125]
hi there ~

i am try to use nervjs for my next.js app, but the build process is failed: 

```js
> Using external babel configuration
> Location: "/Users/xieyiming/code/coderplanets/coderplanets_web/.babelrc"
> Build error occurred
TypeError: external_nervjs_default.a.memo is not a function
    at Object.VZAf (/Users/xieyiming/code/coderplanets/coderplanets_web/.next/server/static/AICcIJUj5W9GBzIteLTj5/pages/_error.js:7575:112)
    at __webpack_require__ (/Users/xieyiming/code/coderplanets/coderplanets_web/.next/server/static/AICcIJUj5W9GBzIteLTj5/pages/_error.js:23:31)
    at Object.Ky/l (/Users/xieyiming/code/coderplanets/coderplanets_web/.next/server/static/AICcIJUj5W9GBzIteLTj5/pages/_error.js:1650:18)
    at __webpack_require__ (/Users/xieyiming/code/coderplanets/coderplanets_web/.next/server/static/AICcIJUj5W9GBzIteLTj5/pages/_error.js:23:31)
    at Module.Y0NT (/Users/xieyiming/code/coderplanets/coderplanets_web/.next/server/static/AICcIJUj5W9GBzIteLTj5/pages/_error.js:8100:79)
    at __webpack_require__ (/Users/xieyiming/code/coderplanets/coderplanets_web/.next/server/static/AICcIJUj5W9GBzIteLTj5/pages/_error.js:23:31)
    at Object.2 (/Users/xieyiming/code/coderplanets/coderplanets_web/.next/server/static/AICcIJUj5W9GBzIteLTj5/pages/_error.js:624:18)
    at __webpack_require__ (/Users/xieyiming/code/coderplanets/coderplanets_web/.next/server/static/AICcIJUj5W9GBzIteLTj5/pages/_error.js:23:31)
    at /Users/xieyiming/code/coderplanets/coderplanets_web/.next/server/static/AICcIJUj5W9GBzIteLTj5/pages/_error.js:91:18
    at Object.<anonymous> (/Users/xieyiming/code/coderplanets/coderplanets_web/.next/server/static/AICcIJUj5W9GBzIteLTj5/pages/_error.js:94:10)
```

### env

main libs

- reactjs: 16.8.1
- nerv:    latest (1.3.12)
- nextjs: 8.1

os info:  mac OS

### step to reproduce

- clone the [project repo](https://github.com/coderplanets/coderplanets_web/tree/play-nerv)
- npm install &&  npm run build.prod

seems react 16's [memo feature](https://reactjs.org/blog/2018/10/23/react-v-16-6.html) is not supported yet ?

**Comment by yuche** [comment]
Use nervjs@beta version.
