### ISSUE TITLE
nervjs 怎样支持ssr 我拿原来的SSR项目改Nervjs的时候它报错

### ISSUE THREAD

**Issue by twins49** [NervJS/nerv#71]
ReferenceError: Nerv is not defined
    at Object.<anonymous> (D:\www2\nerv-ssr\dist\server-entry.js:1:30414)
    at Object.<anonymous> (D:\www2\nerv-ssr\dist\server-entry.js:1:30573)
    at n (D:\www2\nerv-ssr\dist\server-entry.js:1:186)
    at D:\www2\nerv-ssr\dist\server-entry.js:1:607
    at Object.<anonymous> (D:\www2\nerv-ssr\dist\server-entry.js:1:616)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

**Comment by luanwulin** [comment]
应该用 alias，不应该直接用 nerv 吧

**Comment by twins49** [comment]
我试下

**Comment by yuche** [comment]
alias = {            react: 'nervjs',            'react-dom': 'nervjs',            'react-dom/server': 'nerv-server'        }
